stages:
  format:
    cmd: black src
    deps:
    - src
  lint:
    cmd: flake8 src
    deps:
    - src
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    - data_collection.random_state
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    - model_building.max_depth
    - model_building.min_samples_split
    - model_building.min_samples_leaf
    - model_building.max_features
    - model_building.bootstrap
    - model_building.n_jobs
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
  
