data_collection:
  test_size: 0.3
  random_state: 42

model_building:
  n_estimators: 500
  random_state: 42
  max_depth: null
  min_samples_split: 3
  min_samples_leaf: 2
  max_features: sqrt
  bootstrap: true
  n_jobs: -1